### ISSUE TITLE
Issue regarding custom_url parameter

### ISSUE THREAD

**Issue by dok** [rainforestapp/rainforest-orb#39]
Hey there!

I'm developing on top of this orb, and when I set a custom_url, it doesn't seem to take effect. Looking at the code, I see:

https://github.com/rainforestapp/rainforest-orb/blob/master/src/commands/run_qa.yml#L110-L110

`RUN_COMMAND` is being assigned but not used when invoking the [CLI](https://github.com/rainforestapp/rainforest-orb/blob/master/src/commands/run_qa.yml#L131-L142)?

**Comment by magni-** [comment]
Hi @dok, thanks for reporting this! You're right that `RUN_COMMAND` isn't used by the Orb, this was a bad [copy-paste job](https://github.com/rainforestapp/github-action/commit/60baf47237868ac292f77b663b1cdb0b030aec18#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R101) from the sibling repo.

This is now fixed and a new `v3.1.1` version has been released.
